SitioWeb_Juegos/SitioWeb_Juegos/Controllers/AdminController.cs
using Datos;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SitioWeb_Juegos.Controllers
{
    [Authorize(Roles = "Administrador" )]
    public class AdminController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //// GET: Admin/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/AdminTagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;

namespace SitioWeb_Juegos.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AdminTagsController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();

        // GET: AdminTags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: AdminTags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // GET: AdminTags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminTags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descripcion")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tags);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tags);
        }

        // GET: AdminTags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: AdminTags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tags).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tags);
        }

        // GET: AdminTags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: AdminTags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tags tags = db.Tags.Find(id);
            db.Tags.Remove(tags);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;
using Microsoft.AspNet.Identity;
using Servicios;

namespace SitioWeb_Juegos.Controllers
{
    public class PostsController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();

        // GET: Posts
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo");
            return View(posts.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        [Authorize]
        // GET: Posts/Create
        public ActionResult Create()
        {
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Titulo,Contenido,IdCategoria,IdJuego,FechaPublicacion,Autor,Puntaje,IdEstado,Eliminado,Descripcion")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                posts.FechaPublicacion = DateTime.Now;
                posts.IdEstado = 1;
                posts.Autor = User.Identity.GetUserId();
                db.Posts.Add(posts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion", posts.IdJuego);
            
            return View(posts);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            ViewBag.Autor = new SelectList(db.AspNetUsers, "Id", "Email", posts.Autor);
            ViewBag.IdEstado = new SelectList(db.Estados, "Id", "Descripcion", posts.IdEstado);
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion", posts.IdJuego);
            return View(posts);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Contenido,FechaPublicacion,IdCategoria,Autor,IdJuego,Puntaje,IdEstado,Eliminado,Descripcion")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(posts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Autor = new SelectList(db.AspNetUsers, "Id", "Email", posts.Autor);
            ViewBag.IdEstado = new SelectList(db.Estados, "Id", "Descripcion", posts.IdEstado);
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion", posts.IdJuego);
            return View(posts);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Posts posts = db.Posts.Find(id);
            db.Posts.Remove(posts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult VotarPost(int voto, int IdPost)
        {
            ConsultasPosts consultaspost = new ConsultasPosts();
            var IdAutor = User.Identity.GetUserId();

            Voto model = new Voto();
            model.Usuario = IdAutor;
            model.Cantidad = voto;
            model.IdPost = IdPost;
            var idgenerado = consultaspost.VotarPost(model);
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Categorias(int id)
        {
            var model = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo" && x.Juegos.Categorias.Id == id);

            return View("Index", model.ToList());
        }

        public ActionResult Denunciar()
        {
            ViewBag.Motivo = new SelectList(db.MotivosDenuncia, "Id", "Descripcion");
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/TopController.cs
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SitioWeb_Juegos.Controllers
{
   
    public class TopController : Controller
    {
        private ConsultasUsuarios consultasUsuarios = new ConsultasUsuarios();
        // GET: Top
        public ActionResult _UsuariosTops()
        {
            var model = consultasUsuarios.ObtenerUsuarios();
            return PartialView("_UsuariosTops", model);
        }

        // GET: Top/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Top/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Top/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Top/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Top/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Top/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Top/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_Footer.cshtml
 <!-- Footer -->
<footer class="footer text-center">
    <div class="container">
        <ul class="list-inline mb-5">
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white mr-3" href="#">
                    <i class="icon-social-facebook"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white mr-3" href="#">
                    <i class="icon-social-twitter"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-white" href="#">
                    <i class="icon-social-github"></i>
                </a>
            </li>
        </ul>
        <p class="text-muted small mb-0">JUEGOSeñas Inc.&copy; JUEGOSeñas&reg; - @DateTime.Now.Year</p>
    </div>
</footer>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JUEGOSeñas - @ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    @Styles.Render("~/Content/css")
</head>
<body id="page-top">
    @Html.Partial("_NavigationRight")
    @Html.Partial("_NavigationTop")
    @RenderBody()
    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
</body>
</html>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_NavigationRight.cshtml
<!-- Navigation -->
<a class="menu-toggle rounded" href="#">
    <i class="fas fa-bars"></i>
</a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a class="js-scroll-trigger" href="#page-top"><b>JUEGO</b>Señas</a>
        </li>


        @*Login y Register*@

        @using Microsoft.AspNet.Identity
        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "sidebar-nav" }))
            {
                @Html.AntiForgeryToken()

                <br />
                <br />
                <br />
                <br />
                <li class="sidebar-nav-item">
                    @* Preguntar si es admin llevarlo al ManageAdmin, de lo contrario al Manage*@
                    @Html.ActionLink("Hola " + User.Identity.GetUserName() + "!", "Index", "Admin", routeValues: null, htmlAttributes: new { title = "ManageAdmin" })
                    @*@Html.ActionLink("Hola " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })*@
                </li>
                <li class="sidebar-nav-item">
                    <a href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a>
                </li>

            }
        }
        else
        {
            <hr />
            <li class="sidebar-nav-item">
                @Html.ActionLink("Iniciar sesión", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
            </li>
            <hr />
            <li class="sidebar-nav-item">
                @Html.ActionLink("Registrarse", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
            </li>
            <hr />

        }
    </ul>
</nav>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_NavigationTop.cshtml
@*Barra de navegacion de la parte superior de la página*@
<nav class="navbar navbar-expand-lg navbar-dark">
    <a href="/Home/Index" class="navbar-brand"><b>JUEGO</b>Señas</a>
    <button class="navbar-toggler" type="button" data-target="#navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a href="/Home/Index" class="nav-link">Inicio</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Categorías</a>
                <div class="dropdown-menu" aria-labelledby="navdrop">
                    @{
                        Html.RenderAction("_NavigationCategorias", "Categorias");
                    }
                </div>
            </li>

            <li class="nav-item">
                <a href="/Posts/Index" class="nav-link">Reviews</a>
            </li>
            <li class="nav-item">
                <a href="/Home/About" class="nav-link">Tops</a>
            </li>
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    <a href="/Posts/Create" class="nav-link">Crear Review</a>
                </li>
                if (User.IsInRole("Administrador"))
                {
                    <li class="nav-item">
                        <a href="/Admin/Index" class="nav-link">Administrar</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a href="/Admin/Index" class="nav-link">Perfil de Usuario</a>
                    </li>
                }
            }

        </ul>
    </div>
</nav>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_SidebarAdmin.cshtml
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Index","Admin")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminUsuarios")">
            <i class="fas fa-fw fa-table"></i>
            <span>Usuarios</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminPosts")">
            <i class="fas fa-fw fa-table"></i>
            <span>Posts</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminCategorias")">
            <i class="fas fa-fw fa-table"></i>
            <span>Categorias</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminJuegos")">
            <i class="fas fa-fw fa-table"></i>
            <span>Juegos</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminTags")">
            <i class="fas fa-fw fa-table"></i>
            <span>Tags</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminDenuncias")">
            <i class="fas fa-fw fa-table"></i>
            <span>Posts Denunciados</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminDenuncias")">
            <i class="fas fa-fw fa-table"></i>
            <span>Comentarios Denunciados</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminEstados")">
            <i class="fas fa-fw fa-table"></i>
            <span>Estados</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index","AdminNoticias")">
            <i class="fas fa-fw fa-table"></i>
            <span>Noticias</span>
        </a>
    </li>
</ul>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_UsuariosTops.cshtml
@model IEnumerable<Datos.AspNetUsers>

<div class="card my-4">
     <h5 class="card-header">Ranking Usuarios</h5>
     <div class="card-body"> 
         <ol>
             @foreach (var item in Model.OrderByDescending(x=> x.PuntajeTotal).Take(10))
             {

                 <li>
                 <a href="@Url.Action("Categorias","Posts",new { id = item.Id})">@item.UserName : </a> @item.PuntajeTotal
                </li>

             }
         </ol>
      </div>
</div>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Shared/_Widgets.cshtml
            <!-- Sidebar Widgets Column -->
<div class="col-md-4">
    <!-- Search Widget -->
    <div class="card my-4">
        <h5 class="card-header">Búsqueda</h5>
        <div class="card-body">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar por...">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="button">Buscar!</button>
                </span>
            </div>
        </div>
    </div>
    <!-- Categorias Widget -->
    @{
        Html.RenderAction("_PartialCategorias", "Categorias");
    }

    <!-- Top Usuarios Widget -->
    @{
        Html.RenderAction("_UsuariosTops", "Top");
    }

</div>