SitioWeb_Juegos/SitioWeb_Juegos/Controllers/DenunciasComentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;
using Microsoft.AspNet.Identity;
using Servicios;

namespace SitioWeb_Juegos.Controllers
{
    public class DenunciasComentariosController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();

        // GET: Denuncias/Create
        public ActionResult Create()
        {
            ViewBag.Motivo = new SelectList(db.MotivosDenuncia, "Id", "Descripcion");
            return View();
        }

        // POST: Denuncias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ComentarioDenunciado model,int IdComentario, int IdPost)
        {
            ConsultasDenuncias consultasdenuncias = new ConsultasDenuncias();
            var IdDenunciante = User.Identity.GetUserId();       
            model.Usuario = IdDenunciante;
            model.IdComentario = IdComentario;
            var idgenerado = consultasdenuncias.CrearDenunciaComentario(model);
            //return View(model);

            return RedirectToAction("Details", "Posts", new { id = IdPost });

        }

        public ActionResult CrearDenunciaComentario(string descripcion, int id, int motivo)
        {
            ConsultasDenuncias consultasdenuncias = new ConsultasDenuncias();
            var IdDenunciante = User.Identity.GetUserId();
            ComentarioDenunciado model = new ComentarioDenunciado();
            model.Usuario = IdDenunciante;
            model.Descripcion = descripcion;
            model.IdComentario = id;
            model.Motivo = motivo;
            var idgenerado = consultasdenuncias.CrearDenunciaComentario(model);

            return RedirectToAction("Details", "Posts" /*new { id = idpost }*/);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/DenunciasPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;
using Microsoft.AspNet.Identity;
using Servicios;

namespace SitioWeb_Juegos.Controllers
{
    public class DenunciasPostsController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();

        // GET: Denuncias/Create
        public ActionResult Create()
        {
            ViewBag.Motivo = new SelectList(db.MotivosDenuncia, "Id", "Descripcion");
            return View();
        }

        // POST: Denuncias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostDenunciado model,int IdPost)
        {
            ConsultasDenuncias consultasdenuncias = new ConsultasDenuncias();
            var IdDenunciante = User.Identity.GetUserId();       
            model.Usuario = IdDenunciante;
            model.IdPost = IdPost;
            var idgenerado = consultasdenuncias.CrearDenunciaPost(model);
            //return View(model);

            return RedirectToAction("Index", "Posts");

        }

        public ActionResult CrearDenunciaComentario(string descripcion, int id, int motivo)
        {
            ConsultasDenuncias consultasdenuncias = new ConsultasDenuncias();
            var IdDenunciante = User.Identity.GetUserId();
            ComentarioDenunciado model = new ComentarioDenunciado();
            model.Usuario = IdDenunciante;
            model.Descripcion = descripcion;
            model.IdComentario = id;
            model.Motivo = motivo;
            var idgenerado = consultasdenuncias.CrearDenunciaComentario(model);

            return RedirectToAction("Details", "Posts" /*new { id = idpost }*/);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datos;
using Microsoft.AspNet.Identity;
using Servicios;

namespace SitioWeb_Juegos.Controllers
{
    public class PostsController : Controller
    {
        private BDResennasJuegosEntities db = new BDResennasJuegosEntities();

        // GET: Posts
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo");
            return View(posts.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        [Authorize]
        // GET: Posts/Create
        public ActionResult Create()
        {
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Titulo,Contenido,IdCategoria,IdJuego,FechaPublicacion,Autor,Puntaje,IdEstado,Eliminado,Descripcion")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                posts.FechaPublicacion = DateTime.Now;
                posts.IdEstado = 1;
                posts.Autor = User.Identity.GetUserId();
                db.Posts.Add(posts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion", posts.IdJuego);
            
            return View(posts);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            ViewBag.Autor = new SelectList(db.AspNetUsers, "Id", "Email", posts.Autor);
            ViewBag.IdEstado = new SelectList(db.Estados, "Id", "Descripcion", posts.IdEstado);
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion", posts.IdJuego);
            return View(posts);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Contenido,FechaPublicacion,IdCategoria,Autor,IdJuego,Puntaje,IdEstado,Eliminado,Descripcion")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(posts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Autor = new SelectList(db.AspNetUsers, "Id", "Email", posts.Autor);
            ViewBag.IdEstado = new SelectList(db.Estados, "Id", "Descripcion", posts.IdEstado);
            ViewBag.IdJuego = new SelectList(db.Juegos, "Id", "Descripcion", posts.IdJuego);
            return View(posts);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Posts posts = db.Posts.Find(id);
            if (posts == null)
            {
                return HttpNotFound();
            }
            return View(posts);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Posts posts = db.Posts.Find(id);
            db.Posts.Remove(posts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult VotarPost(int voto, int IdPost)
        {
            ConsultasPosts consultaspost = new ConsultasPosts();
            var IdAutor = User.Identity.GetUserId();

            Voto model = new Voto();
            model.Usuario = IdAutor;
            model.Cantidad = voto;
            model.IdPost = IdPost;
            var idgenerado = consultaspost.VotarPost(model);
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Categorias(int id)
        {
            var model = db.Posts.Include(p => p.AspNetUsers).Include(p => p.Estados).Include(p => p.Juegos).Where(x => x.Estados.Descripcion == "Activo" && x.Juegos.Categorias.Id == id);

            return View("Index", model.ToList());
        }

        public ActionResult Denunciar()
        {
            ViewBag.Motivo = new SelectList(db.MotivosDenuncia, "Id", "Descripcion");
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Create.cshtml
@model Datos.Posts

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Posts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdJuego, "Nombre Juego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdJuego", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdJuego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Delete.cshtml
@model Datos.Posts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Posts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contenido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPublicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPublicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puntaje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puntaje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Eliminado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eliminado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorias.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorias.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estados.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estados.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Juegos.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Juegos.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Details.cshtml
@model Datos.Posts
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Post Content Column -->
            <div class="col-lg-8">
                <!-- Title -->
                <h1>@Model.Titulo</h1>
                <!-- Author -->
                <p class="lead">
                    por
                    <a href="#">@Model.AspNetUsers.UserName</a>  <!--ESTE HREF DEBE LLEVAR AL PERFIL DEL AUTOR-->
                </p>
                <hr>
                <!-- Date/Time -->
                Fecha de publicación: @Model.FechaPublicacion.ToLongDateString()
                <hr>
                <!-- Preview Image -->
                <img class="img-fluid rounded" src="@Model.Juegos.Imagen" alt="Imagen del juego">
                <hr>
                <!-- Post Content -->
                <p>@Model.Contenido</p>
                <hr />
                <!-- Post Puntajes -->
                <h4>Puntos:@Model.Puntaje</h4>        
                @if (User.Identity.IsAuthenticated)
                {
                    if ((User.Identity.GetUserId() != Model.Autor) && (Model.PostDenunciados.Where(x => x.Usuario == User.Identity.GetUserId() && x.IdPost == Model.Id).ToList().Count == 0))
                    {
                        <a class="btn btn-danger" id="btnDenunciarComentario" type="submit" href="@Url.Action("Create","DenunciasPosts",new {IdPost = Model.Id })">Denunciar Post</a>
                    }
                    

                    if ((User.Identity.GetUserId() != Model.Autor) && (Model.Votos.Where(x => x.Usuario == User.Identity.GetUserId() && x.IdPost == Model.Id).ToList().Count == 0))
                    {
                        <!--Contador de Me Gustas-->
                        <div class="qty mt-5">
                            <span class="minus bg-dark">-</span>
                            <input type="number" class="count" id="qty" value="0">
                            <span class="plus bg-dark">+</span>

                            <button type="submit" id="BtnVotar" class="btn btn-primary">Votar</button>
                        </div>

                    }

                    <hr />
                    <!-- Comments Form -->
                    <div class="card my-4">
                        <h5 class="card-header">Deja un comentario:</h5>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <textarea id="Comentario" class="form-control" rows="3"></textarea>
                                </div>
                                <button type="submit" id="BtnComentar" class="btn btn-primary">Comentar</button>
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <h2>¡Debes estar logueado para comentar!</h2>
                    @Html.ActionLink("Iniciar Sesion", "Login", "Account")
                    <hr />
                }

                <!-- Single Comment -->
                <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="#" alt=""> <!-- PONER FOTO DE PERFIL -->
                    <div class="media-body">
                        @foreach (var item in Model.Comentarios.ToList().Where(x => x.Estados.Descripcion == "Activo"))
                        {
                            <h5 class="mt-0">@item.AspNetUsers.UserName <small> el @item.FechaPublicacion</small></h5>
                            @item.Contenido
                            if (User.Identity.IsAuthenticated)
                            {
                                if (User.Identity.Name == item.AspNetUsers.UserName)
                                {

                                    <button type="submit" id="btnEliminarComentario" data-id="@item.Id" class="btn btn-primary">Eliminar</button>
                                }
                                else
                                {
                                    <a class="btn btn-group" id="btnDenunciarComentario" type="submit" href="@Url.Action("Create","DenunciasComentarios",new { IdComentario = item.Id, IdPost = Model.Id })">Denunciar</a>
                                }
                            }
                        }
                    </div>
                </div>
            </div>
                @Html.Partial("_Widgets")
            </div>
    </div>

    <!--Scripts del me gusta-->
    @*<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.count').prop('disabled', true);
            $(document).on('click', '.plus', function () {
                $('.count').val(parseInt($('.count').val()) + 1);
                if ($('.count').val() > 5) {
                    $('.count').val(5);
                }
            });
            $(document).on('click', '.minus', function () {
                $('.count').val(parseInt($('.count').val()) - 1);
                if ($('.count').val() < -5) {
                    $('.count').val(-5);
                }
            });
        });
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#BtnVotar").click(function () {
            var voto = $("#qty").val();
            if (voto != 0)
            {
                $.ajax({
                    url: '/Posts/VotarPost/',
                    data: { Voto: voto, IdPost:@Model.Id},
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {

                        alert("Gracias por Votar!");
                    }
                })
                setTimeout(function () {
                    document.getElementById("BtnVotar").disabled = true;
                    document.getElementById("BtnVotar").innerHTML = "Ya votaste!";
                }, 999999999999999999);
            }
            else {
                alert("Error! El voto no puede ser 0!");
            }
        })
    });
    </script>

    <!--Hace la magia para comentar y ver el comentario creado-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
        $(function() {
        $("#BtnComentar").click(function () {
            var comment = $("#Comentario").val();
            if (comment.trim() != "") //Se puede ingresar espacios y el comentario se guarda igual, el .trim elimina el espacio en blanco y verifica si es vacio
            {
                $.ajax({
                    url: '/Comentarios/CrearComentario/',
                    data: { Comentario: comment, IdPost:@Model.Id},
                    type: 'POST',
                    dataType: 'json',
                    success: function (data) {
                        alert("Gracias por Comentar!");
                    }
                });
            }
            else {
                alert("Error! Comentario Vacio");
            }

        });
    })
    </script>

    <!--Hace la magia para borrar comentario creado-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("button[id=btnEliminarComentario]").click(function () {

                if (confirm('Eliminar comentario?')) //Se puede ingresar espacios y el comentario se guarda igual, el .trim elimina el espacio en blanco y verifica si es vacio
                {
                    $.ajax({
                        url: '/Comentarios/EliminarComentario/',
                        data: { IdComentario: $(this).data("id"), IdPost:@Model.Id},
                        type: 'POST',
                        dataType: 'json',
                        success: function (data) {
                            alert("Comentario Eliminado!");
                        }
                    });
                }

            });
        })
    </script>
</body>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Edit.cshtml
@model Datos.Posts

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Posts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaPublicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPublicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPublicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, "IdCategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, "Autor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Autor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdJuego, "IdJuego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdJuego", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdJuego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Puntaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Puntaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Puntaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEstado, "IdEstado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdEstado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Eliminado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Eliminado)
                    @Html.ValidationMessageFor(model => model.Eliminado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SitioWeb_Juegos/SitioWeb_Juegos/Views/Posts/Index.cshtml
@model IEnumerable<Datos.Posts>
@{
    ViewBag.Title = "Reseñas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="my-4">
                    <b>JUEGOS</b>eñas
                    <small> últimas reseñas</small>
                </h1>
                <!-- Blog Post -->
                @foreach (var Po in Model.OrderByDescending(x => x.FechaPublicacion))
                {
                    <div class="card mb-4">
                        <img class="card-img-top" src="@Po.Juegos.Imagen" alt="Card image cap">
                        <div class="card-body">
                            <h2 class="card-title">@Po.Juegos.Descripcion </h2>
                            <p class="card-text">@Po.Descripcion</p>
                            <a href="@Url.Action("Details", "Posts", new { id = Po.Id })" class="btn btn-primary">Leer más &rarr;</a>

                        </div>
                        <div class="card-footer text-muted">
                            Fecha publicación: @Po.FechaPublicacion por:
                            <a href="#">@Po.AspNetUsers.UserName</a>
                            <h4>Puntos:@Po.Puntaje</h4>
                        </div>
                    </div>
                }
                <!-- Pagination -->
                <ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Antiguas</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Nuevas &rarr;</a>
                    </li>
                </ul>
            </div>
            @Html.Partial("_Widgets")
            
        </div>
        <!-- /.row -->
    </div>
</body>